spring:
#  security:
#    user:
#      name: sai
#      password: 1234
#      roles: ADMIN
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/pixelsReview
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "features"
